import type { Metadata } from 'next'
import { LegalDocument } from '@/components/legal-document'
export const metadata:Metadata={title:'Política de privacidad',description:'Información sobre el tratamiento de datos en The Stack House.',alternates:{canonical:'https://thestackhouse.io/privacidad'},robots:{index:false,follow:true}}
export default function PrivacyPage(){return <LegalDocument title="Política de privacidad">
<section><h2>1. Responsable y contacto</h2><p>Responsable: Ramon Arana Barcelo, bajo el nombre comercial The Stack House. Domicilio: Pedro de Mendoza 253, Buenos Aires, CP 1642, Argentina. Provincia pendiente de confirmar. Teléfono: +34 660 926 641. Para consultas sobre datos personales: <a href="mailto:contact@thestackhouse.io">contact@thestackhouse.io</a>.</p></section>
<section><h2>2. Qué datos se recogen</h2><p>Consultas: nombre, correo electrónico, empresa si se facilita y contenido del mensaje. Auditorías: dirección de la tienda, categoría de productos, mercados, nombre y correo. Reservas: datos y horario facilitados en Google Calendar. Evita enviar información sensible o datos personales de tus clientes en los formularios.</p><p>La infraestructura puede procesar dirección IP, información del navegador, solicitudes y registros técnicos. El sitio utiliza una preferencia de idioma; el área privada de correo emplea una cookie de sesión de hasta ocho horas.</p></section>
<section><h2>3. Para qué se utilizan y base jurídica</h2><p>Atender solicitudes, preparar revisiones, coordinar reuniones y gestionar propuestas o servicios: medidas precontractuales solicitadas o ejecución de la relación contractual, cuando corresponda. Si actúas en representación de una empresa, la gestión de esa comunicación profesional puede basarse en el interés legítimo de atenderla.</p><p>La seguridad y prevención de usos no autorizados responden al interés legítimo de proteger el sitio y los datos. Las obligaciones fiscales o administrativas que correspondan se atenderán por obligación legal. Solicitar una revisión no equivale a aceptar una suscripción publicitaria.</p></section>
<section><h2>4. Proveedores y destinatarios</h2><p>Vercel interviene en alojamiento e infraestructura; Resend en el envío de correos; Google Calendar en las reservas y Google en la gestión de correos cuando las solicitudes llegan al buzón del responsable. Cada servicio recibe los datos necesarios para su función. El formulario de contacto actual registra los datos en logs del servidor; el formulario de auditoría los envía por correo.</p><p>La web integra Google Tag Manager, Microsoft Clarity y Vercel Analytics para medición y análisis de uso. Tag Manager puede cargar otras etiquetas según la configuración de su contenedor, que debe revisarse antes de cerrar esta política.</p><p>Estas empresas pueden tratar datos fuera del Espacio Económico Europeo. Antes de publicar la versión definitiva deben verificarse las entidades contratadas, ubicaciones y garantías de transferencia aplicables; no se presupone que todos los datos permanezcan en Europa.</p></section>
<section><h2>5. Cookies y analítica</h2><p>La preferencia de idioma y la sesión privada cumplen funciones de configuración y autenticación. La analítica puede tratar identificadores e interacciones con la web. Google Tag Manager, Microsoft Clarity y Vercel Analytics solo se cargan tras aceptar la analítica. Elegir «Solo esenciales» mantiene estas integraciones bloqueadas. Puedes cambiar tu elección desde «Preferencias de privacidad»; al rechazar se recarga la página para detener las herramientas activas. La elección se guarda en tu navegador durante seis meses. No se considera que navegar equivalga a consentir.</p><p>Puedes gestionar o eliminar cookies en tu navegador, aunque algunas funciones pueden verse afectadas. El selector no elimina datos ya recibidos por proveedores; para ejercer tus derechos, contacta con el responsable.</p></section>
<section><h2>6. Conservación</h2><p>Los datos de consultas se conservarán durante su gestión y el seguimiento relacionado; los de servicios, durante la relación y los plazos legales aplicables o necesarios para atender responsabilidades. Deben concretarse los periodos de eliminación de correos, registros y analítica antes de aprobar esta política. No se ha establecido aquí un plazo ficticio ni una eliminación automática que el sistema no realiza.</p></section>
<section><h2>7. Tus derechos</h2><p>La Ley argentina 25.326 reconoce los derechos de acceso, rectificación, actualización y, cuando corresponda, supresión o confidencialidad de tus datos personales. Puedes ejercerlos a través del correo de contacto del responsable.</p><p>Cuando resulte aplicable el RGPD, puedes solicitar acceso, rectificación, supresión, oposición, limitación o portabilidad, según las condiciones de cada derecho, y retirar el consentimiento para los tratamientos basados en él. Escribe a <a href="mailto:contact@thestackhouse.io">contact@thestackhouse.io</a>; solo se solicitará información adicional de identidad si es necesaria.</p><p>Puedes reclamar ante la autoridad de protección de datos competente, incluida la de tu residencia habitual, lugar de trabajo o lugar de la supuesta infracción. En Argentina, puedes acudir a la <a href="https://www.argentina.gob.ar/aaip/datospersonales/derechos" target="_blank" rel="noopener noreferrer">Agencia de Acceso a la Información Pública (AAIP)</a>.</p></section>
<section><h2>8. Alcance</h2><p>Esta política cubre la web y las comunicaciones relacionadas. Los tratamientos de datos de compradores realizados por cuenta de clientes en proyectos de ecommerce requieren condiciones e instrucciones específicas. Los servicios externos enlazados, incluido LinkedIn, tienen sus propias políticas.</p></section>
</LegalDocument>}
