import type { Metadata } from 'next'
import { LegalDocument } from '@/components/legal-document'
export const metadata:Metadata={title:'Aviso legal',description:'Identificación y condiciones de uso de The Stack House.',alternates:{canonical:'https://thestackhouse.io/aviso-legal'},robots:{index:false,follow:true}}
export default function LegalPage(){return <LegalDocument title="Aviso legal">
<section><h2>1. Responsable del sitio</h2><p>The Stack House es el nombre comercial utilizado en este sitio. Responsable: Ramon Arana Barcelo. No se presenta como una sociedad constituida.</p><p>Domicilio: Pedro de Mendoza 253, Buenos Aires, CP 1642, Argentina. Provincia pendiente de confirmar.</p><p>Teléfono: <a href="tel:+34660926641">+34 660 926 641</a>.</p><p>Web: thestackhouse.io. Contacto: <a href="mailto:contact@thestackhouse.io">contact@thestackhouse.io</a>.</p></section>
<section><h2>2. Actividad</h2><p>Servicios para ecommerce: posicionamiento en respuestas de inteligencia artificial, mejora de catálogo y contenidos, personalización de la experiencia de compra, automatización comercial y medición de resultados.</p><p>El alcance, los entregables, los plazos y el precio de cada trabajo se acuerdan mediante una propuesta específica. Enviar una consulta o reservar una llamada no implica contratar un servicio.</p></section>
<section><h2>3. Uso del sitio</h2><p>El sitio ofrece información comercial y contenidos divulgativos. No debe utilizarse para acceder sin autorización a sistemas, suplantar identidades, introducir contenido malicioso o interferir en su funcionamiento.</p></section>
<section><h2>4. Contenidos y resultados</h2><p>Las ilustraciones y demostraciones de la web explican procesos; no constituyen resultados acreditados de clientes. Las recomendaciones de asistentes y buscadores dependen de terceros y pueden cambiar. Las condiciones y compromisos de un servicio serán los establecidos en su propuesta.</p></section>
<section><h2>5. Propiedad intelectual y enlaces</h2><p>Los contenidos propios y elementos de marca pertenecen a su titular o se utilizan con autorización. Las marcas de terceros pertenecen a sus respectivos propietarios y su aparición no implica afiliación o respaldo. Los enlaces externos conducen a servicios con sus propias condiciones.</p></section>
<section><h2>6. Privacidad y contacto</h2><p>El tratamiento de datos se describe en la <a href="/privacidad">Política de privacidad</a>. Para comunicar errores o plantear consultas, escribe a <a href="mailto:contact@thestackhouse.io">contact@thestackhouse.io</a>.</p></section>
</LegalDocument>}
