'use client'
import { useRef, useState } from 'react'
export function MailingComposer(){
 const [to,setTo]=useState(''),[subject,setSubject]=useState(''),[body,setBody]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[success,setSuccess]=useState(false)
 const pending=useRef(false),requestId=useRef('')
 const change=()=>{requestId.current='';setMessage('');setSuccess(false)}
 async function send(e:React.FormEvent){e.preventDefault();if(pending.current)return;pending.current=true;setBusy(true);setMessage('');setSuccess(false);requestId.current ||= crypto.randomUUID()
 try{const res=await fetch('/api/mailing/send',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({to,subject,body,id:requestId.current})});const data=await res.json();if(!res.ok||!data.ok)throw Error(data.error||'No se pudo enviar.');setSuccess(true);setMessage('Resend aceptó el correo para envío.');}catch(err){setMessage(err instanceof Error?err.message:'No se pudo enviar.')}finally{pending.current=false;setBusy(false)}}
 const input='mt-2 w-full rounded-xl border border-zinc-200 bg-white px-4 py-3 outline-none focus:border-emerald-500 focus:ring-2 focus:ring-emerald-100'
 return <><div className="mb-6 flex items-center justify-between gap-4 text-sm text-zinc-500"><span>De: ramon@thestackhouse.io</span><button className="cursor-pointer rounded-lg px-3 py-2 transition-colors hover:bg-zinc-200/70 hover:text-zinc-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500" onClick={async()=>{const res=await fetch('/api/mailing/logout',{method:'POST'});if(res.ok)location.reload();else setMessage('No se pudo cerrar la sesión.')}}>Cerrar sesión</button></div><form onSubmit={send} className="space-y-5 rounded-3xl border border-zinc-200 bg-white p-6 sm:p-8"><fieldset disabled={busy} className="space-y-5 disabled:opacity-60"><label className="block text-sm font-medium">Para<input type="email" required maxLength={254} className={input} value={to} onChange={e=>{change();setTo(e.target.value)}} placeholder="persona@empresa.com"/></label><label className="block text-sm font-medium">Asunto<input required maxLength={200} className={input} value={subject} onChange={e=>{change();setSubject(e.target.value)}} placeholder="Asunto del correo"/></label><label className="block text-sm font-medium">Mensaje<textarea required maxLength={50000} rows={12} className={input+' resize-y font-normal leading-relaxed'} value={body} onChange={e=>{change();setBody(e.target.value)}} placeholder="Escribe tu correo…"/></label></fieldset>{message&&<p role="status" className={success?'text-sm text-emerald-700':'text-sm text-red-700'}>{message}</p>}<div className="flex items-center justify-between gap-4"><p className="text-xs text-zinc-400">Texto simple · conserva los saltos de línea</p><button disabled={busy||success} type="submit" className="rounded-full bg-emerald-700 px-6 py-3 text-sm font-medium text-white disabled:opacity-50">{busy?'Enviando…':success?'Enviado':'Enviar correo'}</button></div>{success&&<button type="button" className="cursor-pointer rounded-lg px-3 py-2 text-sm text-emerald-700 transition-colors hover:bg-emerald-50 hover:text-emerald-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-emerald-500" onClick={()=>{change();setTo('');setSubject('');setBody('')}}>Escribir otro correo</button>}</form></>
}
