// English copy for the existing landing components.
export const english: Record<string, string> = {
  "Más oportunidades para tu ecommerce": "More opportunities for your online store",
  "Tu próximo cliente está": "Your next customer is",
  "buscándote en": "looking for you on",
  "Conviértete en la respuesta.": "Become the answer.",
  "Audita tu tienda": "Audit your store",
  "20 minutos · primera revisión sin costo": "20 minutes · free first review",
  "Seguimiento de visibilidad · vista ilustrativa": "Visibility tracking · illustrative preview",
  "Vista de la herramienta de seguimiento de visibilidad en IA": "Preview of the AI visibility tracking tool",
  "¿Qué cafetera profesional me conviene para abrir una cafetería?": "Which commercial coffee machine should I choose for a new café?",
  "¿Dónde comprar equipamiento de gimnasio con instalación y garantía?": "Where can I buy gym equipment with installation and a warranty?",
  "¿Qué diferencia hay entre estos dos equipos de depilación láser?": "What is the difference between these two laser hair removal systems?",
  "¿Qué proveedor de herramientas industriales tiene servicio técnico?": "Which industrial tool supplier offers technical support?",
  "¿Qué portátil elegir para editar vídeo sin gastar de más?": "Which laptop should I choose for video editing without overspending?",
  "¿Dónde comprar una silla ergonómica con envío a mi ciudad?": "Where can I buy an ergonomic chair with delivery to my city?",
  "¿Qué cámara me recomiendas para fotografiar productos?": "Which camera would you recommend for product photography?",
  "¿Qué tienda ofrece repuestos compatibles con esta máquina?": "Which store stocks spare parts compatible with this machine?",
  "“": "“",
  "”": "”",
  "~29.000 preguntas cada segundo.": "~29,000 questions every second.",
  "La única pregunta es si tú estás en ellas.": "The only question is whether you’re in them.",
  "Entra en la conversación. Deja que tus clientes te encuentren.": "Join the conversation. Let your customers find you.",
  "Un motor de captación que trabaja alrededor de tu infraestructura": "A customer acquisition engine built around your infrastructure",
  "Un catálogo que se entienda": "A catalog that makes sense",
  "Completamos atributos, compatibilidades, usos y condiciones de compra. Corregimos el acceso a tus páginas para que buscadores y asistentes puedan encontrar e interpretar lo que vendes.": "We fill in product attributes, compatibility, use cases and purchase terms. We fix access to your pages so search engines and assistants can find and understand what you sell.",
  "Respuestas que ayudan a elegir": "Answers that help shoppers choose",
  "Creamos y actualizamos comparativas, guías y páginas de producto sobre las dudas de tus compradores. Información concreta que la IA pueda citar y que ayude a decidir una compra.": "We create and update comparisons, guides and product pages around your shoppers' questions. Specific information AI can cite and people can use to make a purchase decision.",
  "Referencias fuera de tu tienda": "References beyond your own store",
  "Identificamos los medios, listados y publicaciones que aparecen en las respuestas de tu categoría. Trabajamos con esas fuentes para construir presencia y respaldo para tu marca.": "We identify the publications, directories and websites that appear in answers about your category. We work with those sources to build visibility and support for your brand.",
  "Saber quién aparece y por qué": "Know who appears and why",
  "Probamos preguntas de compra en distintos motores. Registramos qué marcas recomiendan y qué fuentes citan para elegir dónde intervenir y comparar la evolución.": "We test purchase questions across different AI engines. We record which brands they recommend and which sources they cite, so we can choose where to act and track progress.",
  "Preguntas de compra → fuentes citadas → acciones": "Purchase questions → cited sources → actions",
  "Trabajar con el SEO que ya tienes": "Build on your existing SEO",
  "Partimos del trabajo existente y coordinamos las mejoras con tu equipo o agencia. Sumamos el análisis de respuestas de IA para detectar oportunidades que el ranking de Google, por sí solo, no muestra.": "We start with the work already done and coordinate improvements with your team or agency. We add AI recommendation analysis to find opportunities that Google rankings alone do not reveal.",
  "Mantener la información al día": "Keep your information current",
  "Revisamos qué cambia en las recomendaciones, qué productos se mencionan y si la información es correcta. Actualizamos los activos y las fuentes que podemos gestionar para sostener el trabajo.": "We review changes in recommendations, which products are mentioned and whether the information is accurate. We update the content and sources within our control to keep the work relevant.",
  "Producto": "Product",
  "El comprador llega y sigue sin saber qué modelo necesita.": "The shopper arrives but still does not know which model they need.",
  "Aclaramos usos, diferencias y compatibilidades en las páginas donde decide.": "We clarify use cases, differences and compatibility on the pages where they decide.",
  "Confianza": "Trust",
  "Tiene que buscar garantías, entregas o soporte antes de avanzar.": "They have to search for warranties, delivery details or support before moving forward.",
  "Acercamos las condiciones y la evidencia comercial a la decisión de compra.": "We put purchase terms and supporting evidence close to the buying decision.",
  "Experiencia": "Experience",
  "Ve el mismo mensaje aunque esté comparando productos distintos.": "They see the same message even when comparing different products.",
  "Contacto": "Contact",
  "Pide información y el contexto se pierde entre formularios y vendedores.": "They ask for information and the context gets lost between forms and salespeople.",
  "Mejora": "Improvement",
  "Se hacen cambios en la tienda sin comprobar qué pasa con las ventas.": "The store gets updated without checking what happens to sales.",
  "La recomendación abre la puerta.": "The recommendation opens the door.",
  "Tu tienda tiene que cerrar la compra.": "Your store needs to close the sale.",
  "Una respuesta para cada duda": "An answer to every question",
  "Producto · comparación · condiciones": "Product · comparison · terms",
  "Elegir": "Choose",
  "con información clara": "with clear information",
  "Un siguiente paso sencillo": "A straightforward next step",
  "Compra directa o venta asistida": "Direct purchase or assisted sale",
  "Avanzar": "Proceed",
  "sin perder el contexto": "with context intact",
  "Comprar": "Buy",
  "Consultar": "Ask",
  "Agendar": "Book",
  "“Me interesa este equipo. ¿Podemos verlo?”": "“I'm interested in this equipment. Can we see it?”",
  "Conectamos ese interés con tu equipo comercial.": "We connect that interest to your sales team.",
  "El vendedor recibe una oportunidad con contexto.": "Your salesperson gets an opportunity with context.",
  "Dónde se frena la compra": "Where the purchase stalls",
  "Qué hacemos": "What we do",
  "Revisamos tu tienda y las preguntas de compra": "We review your store and purchase questions",
  "Implementamos sobre lo que ya tienes": "We implement on top of what you have",
  "Medimos, ajustamos y seguimos construyendo": "We measure, adjust and keep building",
  "Cómo funciona": "How it works",
  "Nos encargamos de ponerlo en marcha.": "We get it up and running.",
  "Y de mejorarlo contigo.": "And keep improving it with you.",
  "Presencia en preguntas de compra": "Visibility in purchase questions",
  "Visitas que podemos identificar": "Visits we can identify",
  "qué asistentes envían tráfico y a qué páginas llega": "which assistants send traffic and which pages receive it",
  "Compras y contactos": "Purchases and inquiries",
  "Oportunidades y ventas": "Opportunities and sales",
  "Influencia declarada por el comprador": "AI influence reported by the shopper",
  "Decisiones para el siguiente mes": "Decisions for the next month",
  "Visitas": "Visits",
  "Consultas": "Inquiries",
  "Ventas": "Sales",
  "Ejemplo del recorrido que medimos: visitas, consultas y ventas. Sin cifras de resultados.": "Illustration of the journey we measure: visits, inquiries and sales. No performance figures shown.",
  "Seguimiento de tu ecommerce": "Your store's performance",
  "De la recomendación a la venta": "From recommendation to sale",
  "Un recorrido conectado": "A connected journey",
  "IA → tienda": "AI → store",
  "→ venta": "→ sale",
  "Esquema ilustrativo · cada etapa se mide por separado": "Illustrative diagram · each stage is measured separately",
  "¿Está generando negocio? Vamos a medirlo.": "Is it generating business? Let's measure it.",
  "Lo que necesitas saber": "What you need to know",
  "antes de empezar.": "before getting started.",
  "Veamos qué oportunidades": "Let's explore the opportunities",
  "tiene tu ecommerce.": "for your online store.",
  "20 minutos · sin costo · sin compromiso": "20 minutes · free · no commitment",
  "Blog": "Blog (ES)",
  "The Stack House": "The Stack House",
  "Herramientas": "Tools",
  "UCP Checker": "UCP Checker",
  "Comprueba si tu ecommerce está preparado para vender mediante agentes de IA.": "Check whether your online store is ready to sell through AI agents.",
  "Audita tu preparación para comercio agéntico": "Check your readiness for agentic commerce",
  "Ayudamos a tu ecommerce a aparecer en la IA y convertir ese interés en ventas.": "We help your online store show up in AI and turn that interest into sales.",
  "Sitio": "Website",
  "hello@thestackhouse.com": "hello@thestackhouse.com",
  "©": "©",
  "The Stack House. Todos los derechos reservados.": "The Stack House. All rights reserved.",
  "¿Esto sirve para mi tipo de ecommerce?": "Is this a fit for my type of online store?",
  "¿Y si todavía recibo pocas visitas desde IA?": "What if I still get very little traffic from AI?",
  "Ya tengo una agencia de SEO. ¿Cómo encajan ustedes?": "I already have an SEO agency. How do you fit in?",
  "¿Tengo que cambiar mi tienda o mi CRM?": "Do I have to change my store or CRM?",
  "¿Cuánto trabajo le va a dar a mi equipo?": "How much work will this create for my team?",
  "¿Pueden garantizar recomendaciones o un aumento de ventas?": "Can you guarantee recommendations or an increase in sales?",
  "¿Cuándo voy a ver avances?": "When will I see progress?",
  "¿Cuánto cuesta y qué incluye la primera llamada?": "How much does it cost, and what does the first call include?",
  "Abrir menú": "Open menu",
  "Cerrar menú": "Close menu",
  "Hacemos que te encuentren en la IA y elijan comprar en tu tienda.": "Get found in AI and chosen by shoppers.",
  "Medimos qué visitas, oportunidades y ventas llegan desde la IA.": "Track the visits, leads and sales coming from AI.",
  "Descubre dónde mejorar tu presencia en IA y convertir más visitas en ventas.": "Find opportunities to get seen in AI and turn more visits into sales.",
  "Tu tienda y tus herramientas. Nosotros nos encargamos de hacerlo funcionar.": "Your store and tools. We make them work together.",
  "Detectamos oportunidades en tu tienda y en las respuestas de la IA. Definimos prioridades.": "Find opportunities in your store and AI answers. Set clear priorities.",
  "Optimizamos catálogo y contenido, reforzamos tu presencia y conectamos las ventas.": "Improve your catalog and content, build visibility and connect sales.",
  "Medimos visibilidad y ventas para decidir qué mejorar después.": "Measure visibility and sales to decide what to improve next.",
  "Cuidamos cada paso, desde el primer interés hasta la compra.": "Improve every step, from first interest to purchase.",
  "Conectamos cada consulta con tu equipo de ventas.": "Connect each inquiry to your sales team.",
  "Adaptamos mensajes y productos al comprador.": "Tailor messages and products to the shopper.",
  "Probamos mejoras y medimos su impacto en ventas.": "Test improvements and measure their impact on sales.",
  "Las mejoras también impulsan tus otros canales de venta.": "These improvements also support your other sales channels.",
  "¿Venta consultiva? Conectamos el interés con una consulta o demo.": "Consultative sales? Turn interest into an inquiry or demo.",
  "Producto y garantías claros para decidir.": "Clear product details and warranties.",
  "tu marca, tus competidores y los motores que te recomiendan": "your brand, competitors and AI recommendations",
  "dónde convierten y dónde abandonan": "where visitors convert or leave",
  "del primer contacto al cierre en tu CRM": "from first contact to closed sale in your CRM",
  "cómo dice el cliente que te encontró": "how customers say they found you",
  "qué mantener, mejorar o probar": "what to keep, improve or test",
  "Si tus clientes investigan antes de comprar, puede encajar. Lo evaluamos en la primera llamada.": "If your customers research before buying, it may be a fit. We assess it on the first call.",
  "Ajustamos la inversión al potencial de tu categoría y mejoramos la conversión del tráfico actual.": "Match investment to your category’s potential and improve conversion from existing traffic.",
  "Coordinamos con tu agencia y sumamos presencia en IA y conversión, sin duplicar trabajo.": "Coordinate with your agency and add AI visibility and conversion without duplicating work.",
  "Trabajamos sobre tus herramientas. Revisamos sus límites antes de proponer cambios.": "We build on your tools and check their limits before proposing changes.",
  "Tu equipo aporta accesos y valida la información. Nosotros ejecutamos y damos seguimiento.": "Your team provides access and validates information. We implement and follow up.",
  "No garantizamos recomendaciones ni ventas. Acordamos entregables y medimos los resultados.": "We don’t guarantee recommendations or sales. We agree on deliverables and measure results.",
  "Primero, mejoras en tu tienda y medición. La presencia en IA requiere continuidad.": "Store improvements and tracking come first. AI visibility takes ongoing work.",
  "La revisión de 20 minutos es gratis. Después, definimos alcance y precio según tu tienda.": "The 20-minute review is free. Then we define scope and pricing for your store.",
  "¿Qué hacen para que mi ecommerce aparezca en ChatGPT?": "What do you do to help my store appear in ChatGPT?",
  "Revisamos cómo aparece tu tienda y qué fuentes cita la IA. Con ese diagnóstico, mejoramos catálogo, contenido y referencias externas para que tus productos entren en la selección.": "We review how your store appears and which sources AI cites. Those findings guide improvements to your catalog, content and external references to help your products enter the shortlist.",
  "Si ya tengo SEO, ¿qué aporta The Stack House?": "If I already invest in SEO, what does The Stack House add?",
  "Partimos de tu SEO y coordinamos con tu agencia. Sumamos el análisis de recomendaciones de IA y trabajamos el recorrido desde esa recomendación hasta la compra.": "We build on your SEO and coordinate with your agency. We add analysis of AI recommendations and improve the journey from those recommendations to a purchase.",
  "¿Van a trabajar todo mi catálogo o priorizar ciertos productos?": "Will you work on my entire catalog or prioritize certain products?",
  "Priorizamos productos y preguntas de compra según su valor comercial, las dudas de tus clientes y lo que encontramos en las respuestas de IA. No hace falta rehacerlo todo.": "We prioritize products and purchase questions based on commercial value, customer questions and what we find in AI answers. There is no need to rebuild everything.",
  "¿Qué hacen si aparezco en la IA pero no llegan ventas?": "What do you do if AI mentions my store but sales do not follow?",
  "Revisamos dónde se corta el recorrido: recomendación, visita o compra. Ajustamos páginas, mensajes y llamadas a la acción según la fricción detectada; medimos ventas y oportunidades, además de menciones.": "We find where the journey breaks down: recommendation, visit or purchase. We adjust pages, messaging and calls to action to address that friction, tracking sales and opportunities alongside mentions.",
  "¿Cómo sabré si ChatGPT está generando ventas?": "How will I know whether ChatGPT is generating sales?",
  "Conectamos las visitas identificables desde IA con compras y oportunidades en tu analítica y CRM. Separamos ese origen de la influencia que declara el comprador y señalamos lo que no podemos atribuir.": "We connect identifiable AI referrals to purchases and opportunities in your analytics and CRM. We distinguish those referrals from buyer-reported influence and flag what we cannot attribute.",
  "¿Tengo que cambiar de plataforma o instalar otra herramienta?": "Do I need to change platforms or install another tool?",
  "Trabajamos sobre tu tienda, analítica y CRM. Revisamos qué permiten tus herramientas y acordamos los cambios necesarios antes de implementarlos.": "We work with your store, analytics and CRM. We assess what your tools support and agree on the necessary changes before implementing them.",
  "¿Ustedes implementan las mejoras o las tiene que hacer mi equipo?": "Do you implement the improvements, or does my team have to?",
  "Nosotros ejecutamos las mejoras acordadas y damos seguimiento. Tu equipo facilita accesos y valida datos de producto, condiciones comerciales y contenido técnico.": "We implement the agreed improvements and track progress. Your team provides access and validates product information, commercial terms and technical content.",
  "¿Tiene sentido invertir si hoy casi no recibo tráfico desde IA?": "Is it worth investing if I barely get any AI traffic today?",
  "Lo evaluamos según tu categoría, cómo compran tus clientes y el valor de cada oportunidad. Tener pocas visitas desde IA, por sí solo, no justifica ni descarta la inversión.": "We assess your category, how your customers buy and the value of each opportunity. Low AI traffic alone is not enough to justify or rule out the investment.",
  "¿Cuándo podré ver resultados y qué pueden garantizar?": "When can I expect results, and what can you guarantee?",
  "Tras el diagnóstico, acordamos prioridades, entregables y plazos de implementación. Seguimos la evolución de recomendaciones, oportunidades y ventas; ninguna posición en la IA ni aumento de ingresos está garantizado.": "After the assessment, we agree on priorities, deliverables and implementation timelines. We track recommendations, opportunities and sales; no AI placement or revenue increase is guaranteed.",
  "¿Cómo definen el precio y qué revisamos en la primera llamada?": "How do you set the price, and what happens on the first call?",
  "La revisión inicial de 20 minutos es gratis: vemos tu tienda y las recomendaciones de tu categoría. Con eso, definimos si encaja y qué alcance e inversión tendría el trabajo.": "The initial 20-minute review is free: we look at your store and recommendations in your category. From there, we establish fit, scope and the investment required.",
  "Más visibilidad en IA. Más oportunidades de venta.": "More AI visibility. More sales opportunities.",
  "The Stack House posiciona tu ecommerce en las respuestas de IA y optimiza tu tienda para convertir ese interés en ventas. Trabajamos tu catálogo, contenido y experiencia de compra, y medimos su impacto comercial.": "The Stack House helps your ecommerce business appear in AI answers and optimizes your store to turn that interest into sales. We improve your catalog, content and shopping experience, and measure their business impact.",
  "Vende a través de la IA sin esfuerzo": "Sell through AI, effortlessly",
  "Construimos tu AI layer: catálogo, contenido y autoridad conectados con la personalización y la conversión.": "We build your AI layer: catalog, content and authority connected to personalization and conversion.",
  "Analizamos tu tienda con agentes de IA": "We analyze your store with AI agents",
  "Evaluamos cómo la IA interpreta tu catálogo y responde a las preguntas de tus compradores.": "We assess how AI interprets your catalog and answers your buyers’ questions.",
  "Implementamos la capa de inteligencia artificial": "We implement your artificial intelligence layer",
  "Conectamos catálogo, contenido y herramientas para que la IA entienda lo que vendes y facilite la compra.": "We connect your catalog, content and tools so AI understands what you sell and helps shoppers buy.",
  "Personalizamos experiencias y te posicionamos": "We personalize experiences and build your AI visibility",
  "Adaptamos tu tienda a cada comprador y trabajamos tu presencia en las recomendaciones de IA.": "We tailor your store to each shopper and build your presence in AI recommendations.",
  "Construimos tu motor de captación": "We build your customer acquisition engine",
  "Anticipa lo que busca cada comprador y adapta la experiencia para convertir su interés en ventas.": "It anticipates what each buyer needs and adapts the experience to turn their interest into sales.",
  "Seguimiento de visibilidad": "Visibility tracking",

  // Auditoría (/auditoria)
  "Paso 1 · Tu tienda": "Step 1 · Your store",
  "Paso 2 · Contacto": "Step 2 · Contact",
  "Tu tienda": "Your store",
  "Con esto preparamos la revisión antes de hablar. Cuanto más claro, más útil la llamada.": "This helps us prepare the review before we talk. The clearer, the more useful the call.",
  "URL de la tienda": "Store URL",
  "Categoría de productos": "Product category",
  "Elige una opción": "Choose an option",
  "Salud y estética": "Health & aesthetics",
  "Tecnología y electrónica": "Technology & electronics",
  "Maquinaria y equipamiento profesional": "Machinery & professional equipment",
  "Hogar y mobiliario": "Home & furniture",
  "Moda y accesorios": "Fashion & accessories",
  "Alimentación y bebidas": "Food & beverages",
  "Industrial / B2B": "Industrial / B2B",
  "Otra": "Other",
  "¿Qué vendes?": "What do you sell?",
  "Países o regiones donde vende": "Countries or regions you sell to",
  "España": "Spain",
  "México": "Mexico",
  "Chile": "Chile",
  "Colombia": "Colombia",
  "Resto de LatAm": "Rest of LatAm",
  "Resto de Europa": "Rest of Europe",
  "EE. UU. / Canadá": "US / Canada",
  "Global": "Global",
  "Otros (opcional)": "Others (optional)",
  "Inversión mensual aproximada en publicidad": "Approx. monthly ad spend",
  "Moneda": "Currency",
  "Elige un rango": "Choose a range",
  "No invertimos actualmente": "We don't currently invest",
  "Menos de 1.000": "Under 1,000",
  "1.000 – 5.000": "1,000 – 5,000",
  "5.000 – 15.000": "5,000 – 15,000",
  "15.000 – 50.000": "15,000 – 50,000",
  "Más de 50.000": "Over 50,000",
  "Continuar": "Continue",
  "¿Dónde te escribimos?": "Where should we reach you?",
  "Para enviarte la confirmación y el resumen de la revisión.": "So we can send you the confirmation and the review summary.",
  "Nombre": "Name",
  "Tu nombre": "Your name",
  "Correo profesional": "Work email",
  "Algo salió mal. Escríbenos a": "Something went wrong. Email us at",
  "Atrás": "Back",
  "Enviando…": "Sending…",
  "Elegir hueco para la revisión": "Pick a time for the review",
  "Recibimos los datos de tu tienda.": "We've got your store details.",
  "Falta un paso: elige un hueco de 20 minutos. Completar el formulario no reserva la reunión.": "One step left: pick a 20-minute slot. Filling in the form doesn't book the meeting.",
  "Casi listo. Elige cuándo.": "Almost there. Pick a time.",
  "Reserva 20 minutos. Ya tenemos los datos de tu tienda — no hace falta repetir nada.": "Book 20 minutes. We already have your store details — no need to repeat anything.",
  "Reservar revisión": "Book review",
  "¿No ves el calendario?": "Can't see the calendar?",
  "Ábrelo aquí →": "Open it here →",
  "Audita tu tienda.": "Audit your store.",
  "Cuéntanos sobre tu tienda para preparar la revisión. Dos minutos ahora, y en la llamada de 20 minutos vamos directo a lo tuyo: qué responde la IA cuando preguntan por tu categoría, a quién recomienda y dónde estás tú.": "Tell us about your store so we can prepare the review. Two minutes now, and in the 20-minute call we go straight to what matters: what AI answers when people ask about your category, who it recommends and where you stand.",

  // Servicios (/servicios)
  "Servicios": "Services",
  "Revisemos tu ecommerce": "Let's review your store",
  "Que la IA te recomiende.": "Get recommended by AI.",
  "Y que esa recomendación termine en venta.": "And turn that recommendation into a sale.",
  "Construimos una capa de datos sobre tu tienda y usamos la IA para llevar compradores decididos hasta la compra. No es una web más bonita: es la cadena completa, y cada pieza sostiene a la siguiente.": "We build a data layer over your store and use AI to guide ready-to-buy shoppers all the way to purchase. Not a prettier website: the whole chain, where each piece holds up the next.",
  "Qué resolvemos": "What we solve",
  "Qué recibes": "What you get",
  "Diagnóstico de tu tienda y de cómo te ve la IA": "A read on your store and how AI sees it",
  "No sabes qué responde la IA cuando preguntan por tu categoría, ni a quién recomienda en tu lugar.": "You don't know what AI answers when people ask about your category, or who it recommends instead of you.",
  "Revisamos tu tienda y probamos las preguntas reales de compra de tu sector en los asistentes de IA.": "We review your store and run your sector's real purchase questions through the AI assistants.",
  "Una foto clara de dónde apareces, dónde no y por qué. Y si tu problema no es la IA, te lo decimos.": "A clear picture of where you show up, where you don't and why. And if your problem isn't AI, we'll tell you.",
  "Preparar tu catálogo para que la IA lo entienda": "Preparing your catalog so AI understands it",
  "La IA compara por datos que tu tienda no publica y termina describiéndote mal — o no te nombra.": "AI compares on data your store doesn't publish, so it describes you wrong — or doesn't mention you at all.",
  "Ordenamos y estructuramos los datos de tu catálogo para que las máquinas los lean sin adivinar.": "We organize and structure your catalog data so machines can read it without guessing.",
  "Un catálogo legible para la IA, con la información que decide la compra a la vista.": "A catalog AI can read, with the information that drives the purchase up front.",
  "Contenido y autoridad para entrar en las recomendaciones": "Content and authority to enter the recommendations",
  "La IA recomienda a quien tiene respaldo fuera de su propia web, no a quien más habla de sí mismo.": "AI recommends those backed up beyond their own website, not those who talk about themselves the most.",
  "Creamos el contenido y la presencia externa que hacen que los modelos te tengan en cuenta.": "We create the content and external presence that get the models to consider you.",
  "Material que la IA puede citar y una presencia que crece en las fuentes que consulta.": "Material AI can cite and a growing presence in the sources it consults.",
  "Captar la demanda que llega decidida": "Capturing the demand that arrives ready to buy",
  "Quien llega desde la IA llega listo para comprar; si nadie responde a tiempo, ya compró en otro sitio.": "Shoppers from AI arrive ready to buy; if no one responds in time, they've already bought elsewhere.",
  "Montamos la captación y la atención en tu tienda para que nadie llegue a una puerta cerrada.": "We set up capture and response on your store so no one reaches a closed door.",
  "Cada consulta llega a tu equipo con su contexto, sin caer en el vacío.": "Every inquiry reaches your team with its context, instead of falling through the cracks.",
  "Convertir y personalizar la experiencia": "Converting and personalizing the experience",
  "Tu tienda muestra lo mismo a todos, aunque cada visitante busque algo distinto y venga a confirmar.": "Your store shows the same thing to everyone, even though each visitor wants something different and comes to confirm.",
  "Ajustamos las páginas donde se decide la compra y adaptamos la experiencia a cada visitante.": "We refine the pages where the purchase is decided and adapt the experience to each visitor.",
  "Una tienda que acompaña al comprador informado hasta la compra.": "A store that guides the informed shopper all the way to purchase.",
  "Conectar todo con tus herramientas de venta": "Connecting everything to your sales tools",
  "Los datos viven sueltos entre la web, la analítica y tu CRM, y el origen del comprador se pierde.": "Data lives scattered across your site, analytics and CRM, and the shopper's origin gets lost.",
  "Conectamos la capa de datos con tus herramientas comerciales para que todo fluya solo.": "We connect the data layer to your sales tools so everything flows on its own.",
  "Cada oportunidad y venta enlazada con su origen, sin trabajo manual.": "Every opportunity and sale tied to its origin, with no manual work.",
  "Medir, seguir y mejorar mes a mes": "Measuring, tracking and improving month to month",
  "Se hacen cambios sin comprobar qué pasa con las ventas, y la posición en la IA se pierde sola.": "Changes get made without checking what happens to sales, and your position in AI slips on its own.",
  "Relacionamos lo que hacemos con lo que vendes y ajustamos la prioridad cada mes.": "We connect what we do to what you sell and adjust the priority every month.",
  "Una lectura clara de qué está funcionando y qué toca después.": "A clear read on what's working and what comes next.",
  "Trabajamos con método y medimos cada paso. Lo que no hacemos es prometerte una posición fija en la IA ni un número de ventas: los modelos cambian, y quien te garantice eso te está mintiendo.": "We work with method and measure every step. What we won't do is promise you a fixed position in AI or a sales number: the models change, and anyone who guarantees that is lying to you.",
  "Empieza por saber dónde estás.": "Start by knowing where you stand.",
  "La revisión de 20 minutos es gratis: vemos tu tienda y qué recomienda la IA en tu categoría. De ahí sale el resto.": "The 20-minute review is free: we look at your store and what AI recommends in your category. Everything else follows from there.",

  // Servicios v2 — 3 bloques + banda tecnológica
  "Tu socio de tecnología e IA.": "Your technology and AI partner.",
  "Para que tu negocio venda más.": "So your business sells more.",
  "Construimos una capa de IA a medida alrededor de tu negocio — de la recomendación en los modelos hasta la venta — y la mantenemos aprendiendo mientras tu equipo se dedica a vender.": "We build a custom AI layer around your business — from the recommendation inside the models to the sale — and keep it learning while your team focuses on selling.",
  "Que la IA te recomiende": "Get recommended by AI",
  "Entramos en las respuestas donde hoy recomiendan a tu competencia.": "We get you into the answers that recommend your competitors today.",
  "Diagnóstico de cómo te ve la IA en las preguntas de compra de tu categoría.": "A read on how AI sees you in your category's purchase questions.",
  "Catálogo y contenido preparados para que los modelos te entiendan y te citen.": "Catalog and content prepared so the models understand and cite you.",
  "Autoridad y presencia en las fuentes que la IA consulta.": "Authority and presence in the sources AI consults.",
  "Que la demanda termine en venta": "Turn demand into sales",
  "Cuidamos al comprador que llega decidido para que no se pierda en el camino.": "We look after the ready-to-buy shopper so they don't get lost along the way.",
  "Captación y atención para que ninguna consulta caiga en el vacío.": "Capture and response so no inquiry falls through the cracks.",
  "Páginas y experiencia adaptadas a cada visitante para convertir.": "Pages and experience adapted to each visitor to convert.",
  "Conexión con tu equipo comercial y tu CRM, con el origen trazado.": "Connected to your sales team and CRM, with the origin tracked.",
  "Tu capa de optimización, siempre encendida": "Your optimization layer, always on",
  "Una capa de IA sobre tu negocio que mide, aprende y mejora sola.": "An AI layer over your business that measures, learns and improves on its own.",
  "Automatizaciones y agentes de IA que trabajan alrededor de tu operación.": "Automations and AI agents working around your operation.",
  "Medición que conecta lo que hacemos con lo que vendes.": "Measurement that ties what we do to what you sell.",
  "Mejora continua: qué mantener, qué probar y qué sigue.": "Continuous improvement: what to keep, what to test and what comes next.",
  "El equipo de tecnología e IA que tu negocio no tiene dentro.": "The technology and AI team your business doesn't have in-house.",
  "Montamos los sistemas que hacen que te encuentren, te elijan y te compren: IA aplicada, automatización y datos, conectados a tu operación comercial. Todo a medida, todo medido contra ventas.": "We build the systems that get you found, chosen and bought from: applied AI, automation and data, connected to your commercial operation. All custom, all measured against sales.",
  "IA aplicada": "Applied AI",
  "Automatización": "Automation",
  "Agentes de IA": "AI agents",
  "Integración de datos": "Data integration",
  "Conversión": "Conversion",
  "Analítica": "Analytics"
}
