import { translate } from "@/lib/translate"
import { NextRequest, NextResponse } from "next/server"
import { landingFaqs } from "@/lib/landing-copy"

const markdown = "# The Stack House — Visibilidad en IA y conversión para ecommerce\n\nHacemos que te encuentren en la IA y elijan comprar en tu tienda.\n\n## Cómo ayudamos a que aparezcan tus productos\n\n- Completamos atributos, compatibilidades, usos y condiciones del catálogo y corregimos el acceso a las páginas.\n- Creamos y actualizamos comparativas, guías y páginas de producto que responden preguntas de compra.\n- Identificamos fuentes externas relevantes y trabajamos para construir presencia y respaldo para la marca.\n- Medimos recomendaciones y fuentes citadas en consultas de compra, con una configuración comparable.\n- Coordinamos las mejoras con el SEO y el equipo existentes, y mantenemos la información actualizada.\n\n## Cómo trabajamos la conversión\n\nMejoramos páginas de producto, comparaciones, garantías, condiciones, formularios y llamadas a la acción. Adaptamos la experiencia según las señales disponibles y conectamos consultas, agenda y CRM para conservar el contexto y dar seguimiento. Trabajamos con compra directa y venta asistida por consulta, presupuesto o demo.\n\n## Cómo trabajamos contigo\n\n1. Revisamos tienda, catálogo, preguntas de compra y recorrido comercial. Acordamos alcance, inversión y medición.\n2. Implementamos sobre la plataforma y las herramientas existentes. El cliente aporta accesos y valida información; The Stack House coordina y ejecuta.\n3. Medimos recomendaciones, visitas, compras y oportunidades para decidir las siguientes mejoras.\n\n## Medición\n\nConectamos presencia en IA, visitas identificables, compras, contactos y resultados registrados en el CRM. Distinguimos el origen rastreable de la influencia declarada por el comprador y señalamos lo que no se puede atribuir. No garantizamos recomendaciones ni un aumento de ventas.\n\n## Primer paso\n\nPrimera revisión sin costo de 20 minutos. Revisamos el ecommerce y una muestra de preguntas de compra para identificar oportunidades y valorar el encaje. El alcance y la inversión de implementación se proponen después.\n\n- [Revisemos tu ecommerce](https://thestackhouse.io/auditoria)\n- [Blog](https://thestackhouse.io/blog)\n- [UCP Checker](https://ucp-checker.thestackhouse.io/)\n- [Contacto](https://thestackhouse.io/contacto)\n"

const markdownEn = "# The Stack House — AI visibility and conversion for ecommerce\n\nWe help your online store show up when shoppers ask AI for recommendations. We work on your catalog, content and reputation, then improve your store to turn that interest into sales.\n\n## How we help your products get discovered\n\n- Complete product attributes, compatibility, use cases and purchase terms, and improve access to your pages.\n- Create and update comparisons, guides and product pages that answer purchase questions.\n- Identify relevant external sources and work to build visibility and support for your brand.\n- Track recommendations and cited sources for purchase questions using comparable settings.\n- Coordinate with your existing SEO team and keep information current.\n\n## How we improve conversion\n\nWe improve product pages, comparisons, warranties, terms, forms and calls to action. We adapt the experience to available signals and connect inquiries, scheduling and CRM to preserve context and follow up. We work with both direct purchases and assisted sales through inquiries, quotes or demos.\n\n## How we work with you\n\n1. Review your store, catalog, purchase questions and sales journey. Agree on scope, investment and measurement.\n2. Implement on your existing platform and tools. Your team provides access and validates information; we coordinate and carry out the work.\n3. Measure recommendations, visits, purchases and opportunities to decide what to improve next.\n\n## Measurement\n\nWe connect AI visibility, identifiable visits, purchases, inquiries and CRM results. We distinguish trackable sources from influence reported by the shopper, and flag attribution gaps. We do not guarantee recommendations or increased sales.\n\n## First step\n\nA free 20-minute review of your store and a sample of purchase questions to identify opportunities and assess fit. Implementation scope and investment are proposed afterwards.\n\n- [Let's review your store](https://thestackhouse.io/auditoria)\n- [Blog in Spanish](https://thestackhouse.io/blog)\n- [UCP Checker](https://ucp-checker.thestackhouse.io/)\n- [Contact in Spanish](https://thestackhouse.io/contacto)\n"

export async function GET(request: NextRequest) {
  const locale = request.nextUrl.searchParams.get("lang") === "en" ? "en" : "es"
  const faq = landingFaqs.map(({ question, answer }) => `### ${translate(locale, question)}\n\n${translate(locale, answer)}`).join("\n\n")
  const body = locale === "en" ? markdownEn : markdown
  const heading = locale === "en" ? "Frequently asked questions" : "Preguntas frecuentes"
  return new NextResponse(`${body}\n## ${heading}\n\n${faq}`, {
    headers: {
      "Content-Type": "text/markdown; charset=utf-8",
      "Content-Language": locale,
      "Cache-Control": "private, no-store",
    },
  })
}
